# Generated by Django 4.1.3 on 2024-01-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhpwapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='type',
            new_name='order_type',
        ),
    ]
